<?php
header('Content-Type: application/json; charset=utf-8');
 ?>
 {
 	"files": [
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/bn-1.jpg",
 			"type":"IMAGE",
 			"size":464119
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/section-2-bg.jpg",
 			"type":"IMAGE",
 			"size":572445
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/pattern-1.png",
 			"type":"IMAGE",
 			"size":10188
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/section-3-bg.jpg",
 			"type":"IMAGE",
 			"size":581812
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/section-4-bg.jpg",
 			"type":"IMAGE",
 			"size":391714
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/section-5-bg-l.jpg",
 			"type":"IMAGE",
 			"size":314510
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/section-5-bg-r.jpg",
 			"type":"IMAGE",
 			"size":425038
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/M1_MBDH.jpg",
 			"type":"IMAGE",
 			"size":303327
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_01.jpg",
 			"type":"IMAGE",
 			"size":98859
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_02.jpg",
 			"type":"IMAGE",
 			"size":98281
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_03.jpg",
 			"type":"IMAGE",
 			"size":90451
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_04.jpg",
 			"type":"IMAGE",
 			"size":89237
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_05.jpg",
 			"type":"IMAGE",
 			"size":94983
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_06.jpg",
 			"type":"IMAGE",
 			"size":97036
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_07.jpg",
 			"type":"IMAGE",
 			"size":101049
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_08.jpg",
 			"type":"IMAGE",
 			"size":103945
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_09.jpg",
 			"type":"IMAGE",
 			"size":89825
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_10.jpg",
 			"type":"IMAGE",
 			"size":92743
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_11.jpg",
 			"type":"IMAGE",
 			"size":95978
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_11A.jpg",
 			"type":"IMAGE",
 			"size":94153
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/thumb/M1_12.jpg",
 			"type":"IMAGE",
 			"size":91256
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/M1_MB_tang_4.jpg",
 			"type":"IMAGE",
 			"size":236225
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m1/M1_MB_tang_23.jpg",
 			"type":"IMAGE",
 			"size":254126
 		},

 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/M3_MBDH.jpg",
 			"type":"IMAGE",
 			"size":303327
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_01.jpg",
 			"type":"IMAGE",
 			"size":98859
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_02.jpg",
 			"type":"IMAGE",
 			"size":98281
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_03.jpg",
 			"type":"IMAGE",
 			"size":90451
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_04.jpg",
 			"type":"IMAGE",
 			"size":89237
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_05.jpg",
 			"type":"IMAGE",
 			"size":94983
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_06.jpg",
 			"type":"IMAGE",
 			"size":97036
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_07.jpg",
 			"type":"IMAGE",
 			"size":101049
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_08.jpg",
 			"type":"IMAGE",
 			"size":103945
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_09.jpg",
 			"type":"IMAGE",
 			"size":89825
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_10.jpg",
 			"type":"IMAGE",
 			"size":92743
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_11.jpg",
 			"type":"IMAGE",
 			"size":95978
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_11A.jpg",
 			"type":"IMAGE",
 			"size":94153
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/thumb/M3_12.jpg",
 			"type":"IMAGE",
 			"size":91256
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/M3_MBDH_tang4.jpg",
 			"type":"IMAGE",
 			"size":249114
 		},
 		{
 			"source":"http://metropolis.vinhomes.vn/wp-content/themes/metropolis/assets/images/surfaces/m3/M3_MBDH_tang23.jpg",
 			"type":"IMAGE",
 			"size":245631
 		}
 	]
 }
